// <auto-generated />
using System;
using MS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260127162204_Mig_20260127_232156")]
    partial class Mig_20260127_232156
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MS.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancellationReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentTime");

                    b.HasIndex("PatientId");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("DoctorId", "AppointmentTime");

                    b.HasIndex("FacilityId", "SpecialtyId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MS.Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AcademicTitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcademicTitleVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("BioEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BioVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000001"),
                            AcademicTitleEn = "PhD., MD.",
                            AcademicTitleVi = "Tiến sĩ, Bác sĩ",
                            AverageRating = 4.7999999999999998,
                            BioEn = "Cardiologist with 20 years of experience",
                            BioVi = "Chuyên gia tim mạch với 20 năm kinh nghiệm",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7102),
                            Email = "bs.an@vinmec.com",
                            FullName = "TS.BS Nguyễn Văn An",
                            IsActive = true,
                            PhoneNumber = "0901234567",
                            PhotoUrl = "https://vinmec-static.s3.amazonaws.com/dr-an.jpg",
                            RatingCount = 150,
                            SpecialtyId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            YearsOfExperience = 20
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000002"),
                            AcademicTitleEn = "Assoc. Prof., PhD.",
                            AcademicTitleVi = "Phó Giáo sư, Tiến sĩ",
                            AverageRating = 4.9000000000000004,
                            BioEn = "Leading oncology specialist",
                            BioVi = "Chuyên gia ung thư hàng đầu",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7105),
                            Email = "pgs.binh@vinmec.com",
                            FullName = "PGS.TS Trần Thị Bình",
                            IsActive = true,
                            PhoneNumber = "0902345678",
                            PhotoUrl = "https://vinmec-static.s3.amazonaws.com/dr-binh.jpg",
                            RatingCount = 200,
                            SpecialtyId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            YearsOfExperience = 25
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000003"),
                            AcademicTitleEn = "Specialist Doctor Level 2",
                            AcademicTitleVi = "Bác sĩ Chuyên khoa 2",
                            AverageRating = 4.7000000000000002,
                            BioEn = "Experienced pediatrician",
                            BioVi = "Bác sĩ Nhi khoa giàu kinh nghiệm",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7111),
                            Email = "bs.cuong@vinmec.com",
                            FullName = "BS.CK2 Lê Văn Cường",
                            IsActive = true,
                            PhoneNumber = "0903456789",
                            PhotoUrl = "https://vinmec-static.s3.amazonaws.com/dr-an.jpg",
                            RatingCount = 120,
                            SpecialtyId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000004"),
                            AcademicTitleEn = "PhD., MD.",
                            AcademicTitleVi = "Tiến sĩ, Bác sĩ",
                            AverageRating = 4.9000000000000004,
                            BioEn = "Obstetrics and gynecology specialist",
                            BioVi = "Chuyên gia sản phụ khoa",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7115),
                            Email = "bs.dung@vinmec.com",
                            FullName = "TS.BS Phạm Thị Dung",
                            IsActive = true,
                            PhoneNumber = "0904567890",
                            PhotoUrl = "https://vinmec-static.s3.amazonaws.com/dr-an.jpg",
                            RatingCount = 180,
                            SpecialtyId = new Guid("a0000000-0000-0000-0000-000000000004"),
                            YearsOfExperience = 18
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000005"),
                            AcademicTitleEn = "Specialist Doctor Level 1",
                            AcademicTitleVi = "Bác sĩ Chuyên khoa 1",
                            AverageRating = 4.5999999999999996,
                            BioEn = "Gastroenterology specialist",
                            BioVi = "Chuyên gia tiêu hóa - gan mật",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7132),
                            Email = "bs.em@vinmec.com",
                            FullName = "BS.CK1 Hoàng Văn Em",
                            IsActive = true,
                            PhoneNumber = "0905678901",
                            PhotoUrl = "https://vinmec-static.s3.amazonaws.com/dr-an.jpg",
                            RatingCount = 95,
                            SpecialtyId = new Guid("a0000000-0000-0000-0000-000000000005"),
                            YearsOfExperience = 12
                        });
                });

            modelBuilder.Entity("MS.Domain.Entities.DoctorAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("DoctorId", "DayOfWeek");

                    b.ToTable("DoctorAvailabilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da000000-0000-0000-0000-000000000001"),
                            DayOfWeek = 1,
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000001"),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            FacilityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SlotDurationMinutes = 15,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("da000000-0000-0000-0000-000000000002"),
                            DayOfWeek = 3,
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000001"),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            FacilityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SlotDurationMinutes = 15,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("da000000-0000-0000-0000-000000000003"),
                            DayOfWeek = 5,
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000001"),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            FacilityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SlotDurationMinutes = 15,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("da000000-0000-0000-0000-000000000004"),
                            DayOfWeek = 2,
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000002"),
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            FacilityId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            SlotDurationMinutes = 20,
                            StartTime = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("da000000-0000-0000-0000-000000000005"),
                            DayOfWeek = 4,
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000002"),
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            FacilityId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            SlotDurationMinutes = 20,
                            StartTime = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("da000000-0000-0000-0000-000000000006"),
                            DayOfWeek = 1,
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000003"),
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            FacilityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SlotDurationMinutes = 15,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("da000000-0000-0000-0000-000000000007"),
                            DayOfWeek = 2,
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000003"),
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            FacilityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SlotDurationMinutes = 15,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("da000000-0000-0000-0000-000000000008"),
                            DayOfWeek = 3,
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000003"),
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            FacilityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SlotDurationMinutes = 15,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("MS.Domain.Entities.DoctorFacility", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasKey("DoctorId", "FacilityId");

                    b.HasIndex("FacilityId");

                    b.ToTable("DoctorFacilities");

                    b.HasData(
                        new
                        {
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000001"),
                            FacilityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssignedDate = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7157),
                            IsPrimary = true
                        },
                        new
                        {
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000001"),
                            FacilityId = new Guid("22222222-2222-2222-2222-222222222222"),
                            AssignedDate = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7159),
                            IsPrimary = false
                        },
                        new
                        {
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000002"),
                            FacilityId = new Guid("22222222-2222-2222-2222-222222222222"),
                            AssignedDate = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7161),
                            IsPrimary = true
                        },
                        new
                        {
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000003"),
                            FacilityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssignedDate = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7162),
                            IsPrimary = true
                        },
                        new
                        {
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000003"),
                            FacilityId = new Guid("33333333-3333-3333-3333-333333333333"),
                            AssignedDate = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7164),
                            IsPrimary = false
                        },
                        new
                        {
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000004"),
                            FacilityId = new Guid("22222222-2222-2222-2222-222222222222"),
                            AssignedDate = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7165),
                            IsPrimary = true
                        },
                        new
                        {
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000004"),
                            FacilityId = new Guid("33333333-3333-3333-3333-333333333333"),
                            AssignedDate = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7166),
                            IsPrimary = false
                        },
                        new
                        {
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000005"),
                            FacilityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssignedDate = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7168),
                            IsPrimary = true
                        });
                });

            modelBuilder.Entity("MS.Domain.Entities.DoctorLanguage", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.HasKey("DoctorId", "Language");

                    b.ToTable("DoctorLanguages");

                    b.HasData(
                        new
                        {
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000001"),
                            Language = 0
                        },
                        new
                        {
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000001"),
                            Language = 1
                        },
                        new
                        {
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000002"),
                            Language = 0
                        },
                        new
                        {
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000002"),
                            Language = 1
                        },
                        new
                        {
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000003"),
                            Language = 0
                        },
                        new
                        {
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000004"),
                            Language = 0
                        },
                        new
                        {
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000004"),
                            Language = 1
                        },
                        new
                        {
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000005"),
                            Language = 0
                        });
                });

            modelBuilder.Entity("MS.Domain.Entities.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "458 Minh Khai, Hai Bà Trưng, Hà Nội",
                            City = "Hà Nội",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(6900),
                            Email = "info.timescity@vinmec.com",
                            IsActive = true,
                            NameEn = "Vinmec Times City International Hospital",
                            NameVi = "Bệnh viện Đa khoa Quốc tế Vinmec Times City",
                            Phone = "024 3974 3556",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "208 Nguyễn Hữu Cảnh, Bình Thạnh, TP. Hồ Chí Minh",
                            City = "TP. Hồ Chí Minh",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(6906),
                            Email = "info.centralpark@vinmec.com",
                            IsActive = true,
                            NameEn = "Vinmec Central Park International Hospital",
                            NameVi = "Bệnh viện Đa khoa Quốc tế Vinmec Central Park",
                            Phone = "028 3622 1166",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Address = "107-109 Nguyễn Văn Linh, Thanh Khê, Đà Nẵng",
                            City = "Đà Nẵng",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(6908),
                            Email = "info.danang@vinmec.com",
                            IsActive = true,
                            NameEn = "Vinmec Da Nang Hospital",
                            NameVi = "Bệnh viện Đa khoa Vinmec Đà Nẵng",
                            Phone = "023 6371 1111",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Address = "Lô D20 Lê Hồng Phong, Ngô Quyền, Hải Phòng",
                            City = "Hải Phòng",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(6912),
                            Email = "info.haiphong@vinmec.com",
                            IsActive = true,
                            NameEn = "Vinmec Hai Phong Hospital",
                            NameVi = "Bệnh viện Đa khoa Vinmec Hải Phòng",
                            Phone = "022 5730 9888",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Address = "Khu đô thị Vinpearl, Vĩnh Nguyên, Nha Trang",
                            City = "Khánh Hòa",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(6914),
                            Email = "info.nhatrang@vinmec.com",
                            IsActive = true,
                            NameEn = "Vinmec Nha Trang Hospital",
                            NameVi = "Bệnh viện Đa khoa Vinmec Nha Trang",
                            Phone = "025 8390 0168",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Address = "Đảo Tuần Châu, Hạ Long, Quảng Ninh",
                            City = "Quảng Ninh",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(6916),
                            Email = "info.halong@vinmec.com",
                            IsActive = true,
                            NameEn = "Vinmec Ha Long Hospital",
                            NameVi = "Bệnh viện Đa khoa Vinmec Hạ Long",
                            Phone = "020 3382 8188",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Address = "Bãi Dài, Gành Dầu, Phú Quốc, Kiên Giang",
                            City = "Kiên Giang",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(6919),
                            Email = "info.phuquoc@vinmec.com",
                            IsActive = true,
                            NameEn = "Vinmec Phu Quoc Hospital",
                            NameVi = "Bệnh viện Đa khoa Vinmec Phú Quốc",
                            Phone = "029 7398 5588",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Address = "Đường 30/4, Xuân Khánh, Ninh Kiều, Cần Thơ",
                            City = "Cần Thơ",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(6921),
                            Email = "info.cantho@vinmec.com",
                            IsActive = true,
                            NameEn = "Vinmec Can Tho Hospital",
                            NameVi = "Bệnh viện Đa khoa Vinmec Cần Thơ",
                            Phone = "029 2368 3003",
                            Type = 0
                        });
                });

            modelBuilder.Entity("MS.Domain.Entities.MessageTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code", "Language")
                        .IsUnique();

                    b.ToTable("MessageTranslations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_2000",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7390),
                            Language = "vi",
                            Text = "Thành công"
                        },
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_2000",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7395),
                            Language = "en",
                            Text = "Success"
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_2001",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7397),
                            Language = "vi",
                            Text = "Đặt lịch khám thành công"
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_2001",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7399),
                            Language = "en",
                            Text = "Appointment booked successfully"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_2002",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7400),
                            Language = "vi",
                            Text = "Lịch hẹn đang chờ xác nhận"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_2002",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7402),
                            Language = "en",
                            Text = "Appointment pending confirmation"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_2003",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7404),
                            Language = "vi",
                            Text = "Lịch hẹn đã được xác nhận"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_2003",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7441),
                            Language = "en",
                            Text = "Appointment confirmed"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_2004",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7443),
                            Language = "vi",
                            Text = "Hủy lịch hẹn thành công"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_2004",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7445),
                            Language = "en",
                            Text = "Appointment cancelled successfully"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_2005",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7447),
                            Language = "vi",
                            Text = "Tạo hồ sơ bệnh nhân thành công"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_2005",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7448),
                            Language = "en",
                            Text = "Patient record created successfully"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_2006",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7450),
                            Language = "vi",
                            Text = "Cập nhật thông tin bệnh nhân thành công"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_2006",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7451),
                            Language = "en",
                            Text = "Patient information updated successfully"
                        },
                        new
                        {
                            Id = new Guid("00000008-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_4001",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7453),
                            Language = "vi",
                            Text = "Số điện thoại không hợp lệ"
                        },
                        new
                        {
                            Id = new Guid("00000008-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_4001",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7454),
                            Language = "en",
                            Text = "Invalid phone number"
                        },
                        new
                        {
                            Id = new Guid("00000009-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_4002",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7456),
                            Language = "vi",
                            Text = "Ngày sinh không hợp lệ"
                        },
                        new
                        {
                            Id = new Guid("00000009-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_4002",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7458),
                            Language = "en",
                            Text = "Invalid date of birth"
                        },
                        new
                        {
                            Id = new Guid("00000010-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_4003",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7459),
                            Language = "vi",
                            Text = "Thiếu trường bắt buộc"
                        },
                        new
                        {
                            Id = new Guid("00000010-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_4003",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7461),
                            Language = "en",
                            Text = "Missing required field"
                        },
                        new
                        {
                            Id = new Guid("00000011-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_4004",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7462),
                            Language = "vi",
                            Text = "Thời gian khám không hợp lệ"
                        },
                        new
                        {
                            Id = new Guid("00000011-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_4004",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7464),
                            Language = "en",
                            Text = "Invalid appointment time"
                        },
                        new
                        {
                            Id = new Guid("00000012-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_4005",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7465),
                            Language = "vi",
                            Text = "Thời gian khám đã qua"
                        },
                        new
                        {
                            Id = new Guid("00000012-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_4005",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7467),
                            Language = "en",
                            Text = "Appointment time is in the past"
                        },
                        new
                        {
                            Id = new Guid("00000013-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_4006",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7468),
                            Language = "vi",
                            Text = "Bác sĩ không có lịch khám"
                        },
                        new
                        {
                            Id = new Guid("00000013-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_4006",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7469),
                            Language = "en",
                            Text = "Doctor not available"
                        },
                        new
                        {
                            Id = new Guid("00000014-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_4007",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7471),
                            Language = "vi",
                            Text = "Khung giờ đã được đặt"
                        },
                        new
                        {
                            Id = new Guid("00000014-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_4007",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7472),
                            Language = "en",
                            Text = "Time slot already booked"
                        },
                        new
                        {
                            Id = new Guid("00000015-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_4008",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7473),
                            Language = "vi",
                            Text = "Không tìm thấy cơ sở y tế"
                        },
                        new
                        {
                            Id = new Guid("00000015-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_4008",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7474),
                            Language = "en",
                            Text = "Facility not found"
                        },
                        new
                        {
                            Id = new Guid("00000016-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_4009",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7476),
                            Language = "vi",
                            Text = "Không tìm thấy chuyên khoa"
                        },
                        new
                        {
                            Id = new Guid("00000016-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_4009",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7477),
                            Language = "en",
                            Text = "Specialty not found"
                        },
                        new
                        {
                            Id = new Guid("00000017-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_4010",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7478),
                            Language = "vi",
                            Text = "Không tìm thấy bệnh nhân"
                        },
                        new
                        {
                            Id = new Guid("00000017-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_4010",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7481),
                            Language = "en",
                            Text = "Patient not found"
                        },
                        new
                        {
                            Id = new Guid("00000018-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_4011",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7482),
                            Language = "vi",
                            Text = "Không tìm thấy bác sĩ"
                        },
                        new
                        {
                            Id = new Guid("00000018-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_4011",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7483),
                            Language = "en",
                            Text = "Doctor not found"
                        },
                        new
                        {
                            Id = new Guid("00000019-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_4012",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7485),
                            Language = "vi",
                            Text = "Không tìm thấy lịch hẹn"
                        },
                        new
                        {
                            Id = new Guid("00000019-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_4012",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7486),
                            Language = "en",
                            Text = "Appointment not found"
                        },
                        new
                        {
                            Id = new Guid("00000020-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_4013",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7487),
                            Language = "vi",
                            Text = "Trạng thái lịch hẹn không hợp lệ"
                        },
                        new
                        {
                            Id = new Guid("00000020-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_4013",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7488),
                            Language = "en",
                            Text = "Invalid appointment status"
                        },
                        new
                        {
                            Id = new Guid("00000021-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_4014",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7490),
                            Language = "vi",
                            Text = "Không có quyền truy cập"
                        },
                        new
                        {
                            Id = new Guid("00000021-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_4014",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7491),
                            Language = "en",
                            Text = "Unauthorized access"
                        },
                        new
                        {
                            Id = new Guid("00000022-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_4015",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7492),
                            Language = "vi",
                            Text = "Lịch hẹn trùng lặp"
                        },
                        new
                        {
                            Id = new Guid("00000022-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_4015",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7494),
                            Language = "en",
                            Text = "Duplicate appointment"
                        },
                        new
                        {
                            Id = new Guid("00000023-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_4016",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7495),
                            Language = "vi",
                            Text = "Thông tin đăng nhập không đúng"
                        },
                        new
                        {
                            Id = new Guid("00000023-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_4016",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7496),
                            Language = "en",
                            Text = "Invalid credentials"
                        },
                        new
                        {
                            Id = new Guid("00000024-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_4017",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7497),
                            Language = "vi",
                            Text = "Email đã tồn tại trong hệ thống"
                        },
                        new
                        {
                            Id = new Guid("00000024-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_4017",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7499),
                            Language = "en",
                            Text = "Email already exists"
                        },
                        new
                        {
                            Id = new Guid("00000025-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_4018",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7500),
                            Language = "vi",
                            Text = "Số điện thoại đã được sử dụng"
                        },
                        new
                        {
                            Id = new Guid("00000025-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_4018",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7501),
                            Language = "en",
                            Text = "Phone number already in use"
                        },
                        new
                        {
                            Id = new Guid("00000026-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_5001",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7503),
                            Language = "vi",
                            Text = "Lỗi hệ thống"
                        },
                        new
                        {
                            Id = new Guid("00000026-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_5001",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7504),
                            Language = "en",
                            Text = "Internal server error"
                        },
                        new
                        {
                            Id = new Guid("00000027-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_5002",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7530),
                            Language = "vi",
                            Text = "Lỗi cơ sở dữ liệu"
                        },
                        new
                        {
                            Id = new Guid("00000027-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_5002",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7532),
                            Language = "en",
                            Text = "Database error"
                        },
                        new
                        {
                            Id = new Guid("00000028-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_5003",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7533),
                            Language = "vi",
                            Text = "Dịch vụ không khả dụng"
                        },
                        new
                        {
                            Id = new Guid("00000028-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_5003",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7534),
                            Language = "en",
                            Text = "Service unavailable"
                        },
                        new
                        {
                            Id = new Guid("00000029-0000-0000-0000-000000000001"),
                            Code = "APP_MESSAGE_5004",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7536),
                            Language = "vi",
                            Text = "Lỗi dịch vụ bên ngoài"
                        },
                        new
                        {
                            Id = new Guid("00000029-0000-0000-0000-000000000002"),
                            Code = "APP_MESSAGE_5004",
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7537),
                            Language = "en",
                            Text = "External service error"
                        });
                });

            modelBuilder.Entity("MS.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IdentityCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MS.Domain.Entities.Specialty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7049),
                            DescriptionEn = "Specializes in cardiovascular diseases",
                            DescriptionVi = "Chuyên điều trị các bệnh lý tim mạch",
                            DisplayOrder = 1,
                            IconUrl = "https://vinmec-static.s3.amazonaws.com/icons/cardiology.png",
                            IsActive = true,
                            NameEn = "Cardiology Center",
                            NameVi = "Trung tâm Tim mạch"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7052),
                            DescriptionEn = "Cancer treatment specialists",
                            DescriptionVi = "Chuyên điều trị ung thư",
                            DisplayOrder = 2,
                            IconUrl = "https://vinmec-static.s3.amazonaws.com/icons/oncology.png",
                            IsActive = true,
                            NameEn = "Oncology Center",
                            NameVi = "Trung tâm Ung bướu"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7054),
                            DescriptionEn = "Children's healthcare",
                            DescriptionVi = "Chăm sóc sức khỏe trẻ em",
                            DisplayOrder = 3,
                            IconUrl = "https://vinmec-static.s3.amazonaws.com/icons/cardiology.png",
                            IsActive = true,
                            NameEn = "Pediatrics Center",
                            NameVi = "Trung tâm Nhi"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7057),
                            DescriptionEn = "Obstetrics and reproductive health",
                            DescriptionVi = "Sản phụ khoa và sức khỏe sinh sản",
                            DisplayOrder = 4,
                            IconUrl = "https://vinmec-static.s3.amazonaws.com/icons/cardiology.png",
                            IsActive = true,
                            NameEn = "Women's Health Center",
                            NameVi = "Trung tâm Sức khỏe phụ nữ"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7059),
                            DescriptionEn = "Digestive system and liver diseases",
                            DescriptionVi = "Chuyên khoa tiêu hóa và gan mật",
                            DisplayOrder = 5,
                            IconUrl = "https://vinmec-static.s3.amazonaws.com/icons/cardiology.png",
                            IsActive = true,
                            NameEn = "Gastroenterology",
                            NameVi = "Tiêu hóa - Gan mật"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7061),
                            DescriptionEn = "Neurological disorders diagnosis and treatment",
                            DescriptionVi = "Chẩn đoán và điều trị bệnh lý thần kinh",
                            DisplayOrder = 6,
                            IconUrl = "https://vinmec-static.s3.amazonaws.com/icons/cardiology.png",
                            IsActive = true,
                            NameEn = "Neurology",
                            NameVi = "Thần kinh"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7063),
                            DescriptionEn = "Trauma and orthopedic treatment",
                            DescriptionVi = "Điều trị chấn thương và chỉnh hình",
                            DisplayOrder = 7,
                            IconUrl = "https://vinmec-static.s3.amazonaws.com/icons/cardiology.png",
                            IsActive = true,
                            NameEn = "Orthopedics & Sports Medicine",
                            NameVi = "Chấn thương chỉnh hình - Y học thể thao"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7065),
                            DescriptionEn = "Comprehensive eye care",
                            DescriptionVi = "Chăm sóc mắt toàn diện",
                            DisplayOrder = 8,
                            IconUrl = "https://vinmec-static.s3.amazonaws.com/icons/cardiology.png",
                            IsActive = true,
                            NameEn = "Eye Center Vinmec-Alina",
                            NameVi = "Trung tâm Mắt Vinmec-Alina"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7067),
                            DescriptionEn = "Premium dental services",
                            DescriptionVi = "Dịch vụ nha khoa cao cấp",
                            DisplayOrder = 9,
                            IconUrl = "https://vinmec-static.s3.amazonaws.com/icons/cardiology.png",
                            IsActive = true,
                            NameEn = "Vinmec-View Premium Dental",
                            NameVi = "Nha khoa Vinmec-View Premium"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7068),
                            DescriptionEn = "Skin care and aesthetics",
                            DescriptionVi = "Chăm sóc da và thẩm mỹ",
                            DisplayOrder = 10,
                            IconUrl = "https://vinmec-static.s3.amazonaws.com/icons/cardiology.png",
                            IsActive = true,
                            NameEn = "Dermatology & Aesthetics",
                            NameVi = "Thẩm mỹ Da liễu"
                        });
                });

            modelBuilder.Entity("MS.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FacilityId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7644),
                            Email = "admin@vinmec.com",
                            FullName = "Quản trị viên hệ thống",
                            IsActive = true,
                            PasswordHash = "AQAAAAEAACcQAAAAEJ9z8ZqI5vYzJ5vZQ5vZQ5vZQ==",
                            PhoneNumber = "0900000000",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 27, 16, 22, 3, 1, DateTimeKind.Utc).AddTicks(7647),
                            Email = "bs.an@vinmec.com",
                            FacilityId = new Guid("11111111-1111-1111-1111-111111111111"),
                            FullName = "TS.BS Nguyễn Văn An",
                            IsActive = true,
                            PasswordHash = "AQAAAAEAACcQAAAAEJ9z8ZqI5vYzJ5vZQ5vZQ5vZQ==",
                            PhoneNumber = "0901234567",
                            Role = 2,
                            Username = "doctor.an"
                        });
                });

            modelBuilder.Entity("MS.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("MS.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MS.Domain.Entities.Facility", "Facility")
                        .WithMany("Appointments")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MS.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MS.Domain.Entities.Specialty", "Specialty")
                        .WithMany("Appointments")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Facility");

                    b.Navigation("Patient");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("MS.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("MS.Domain.Entities.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("MS.Domain.Entities.DoctorAvailability", b =>
                {
                    b.HasOne("MS.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Availabilities")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MS.Domain.Entities.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("MS.Domain.Entities.DoctorFacility", b =>
                {
                    b.HasOne("MS.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Facilities")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MS.Domain.Entities.Facility", "Facility")
                        .WithMany("DoctorFacilities")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("MS.Domain.Entities.DoctorLanguage", b =>
                {
                    b.HasOne("MS.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Languages")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MS.Domain.Entities.User", b =>
                {
                    b.HasOne("MS.Domain.Entities.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("MS.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Availabilities");

                    b.Navigation("Facilities");

                    b.Navigation("Languages");
                });

            modelBuilder.Entity("MS.Domain.Entities.Facility", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorFacilities");
                });

            modelBuilder.Entity("MS.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("MS.Domain.Entities.Specialty", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
