// <auto-generated />
using System;
using MS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311164101_Initial_Reset")]
    partial class Initial_Reset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MS.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("AppointmentTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentTime");

                    b.HasIndex("PatientId");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("DoctorId", "AppointmentTime");

                    b.HasIndex("FacilityId", "SpecialtyId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MS.Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AcademicTitleEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcademicTitleVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("BioEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BioVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AcademicTitleEn = "PhD",
                            AcademicTitleVi = "Tiến sĩ",
                            AvatarUrl = "/assets/images/doctors/john_doe.png",
                            AverageRating = 4.7999999999999998,
                            BioEn = "Internal medicine specialist with 15 years experience",
                            BioVi = "Bác sĩ chuyên khoa nội, 15 năm kinh nghiệm",
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Dr. John Doe",
                            Email = "john.doe@example.com",
                            FullName = "John Doe",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            PhoneNumber = "0123456789",
                            PhotoUrl = "/assets/images/doctors/john_doe.png",
                            RatingCount = 120,
                            SpecialtyId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UserId = new Guid("55555555-5555-5555-5555-555555555557"),
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            AcademicTitleEn = "Master",
                            AcademicTitleVi = "Thạc sĩ",
                            AvatarUrl = "/assets/images/doctors/van_anh.png",
                            AverageRating = 4.9000000000000004,
                            BioEn = "Cardiologist with 12 years experience",
                            BioVi = "Bác sĩ chuyên khoa tim mạch, 12 năm kinh nghiệm",
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Dr. Nguyễn Văn Anh",
                            Email = "van.anh@clinic.vn",
                            FullName = "Nguyễn Văn Anh",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            PhoneNumber = "0987654321",
                            PhotoUrl = "/assets/images/doctors/van_anh.png",
                            RatingCount = 250,
                            SpecialtyId = new Guid("22222222-2222-2222-2222-222222222224"),
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            AcademicTitleEn = "Master",
                            AcademicTitleVi = "Thạc sĩ",
                            AvatarUrl = "/assets/images/doctors/tran_huong.png",
                            AverageRating = 4.7000000000000002,
                            BioEn = "Pediatrician with 8 years experience",
                            BioVi = "Bác sĩ nhi khoa, 8 năm kinh nghiệm",
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Dr. Trần Hương",
                            Email = "huong.tran@clinic.vn",
                            FullName = "Trần Hương",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            PhoneNumber = "0912345678",
                            PhotoUrl = "/assets/images/doctors/tran_huong.png",
                            RatingCount = 180,
                            SpecialtyId = new Guid("22222222-2222-2222-2222-222222222223"),
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            AcademicTitleEn = "PhD",
                            AcademicTitleVi = "Tiến sĩ",
                            AvatarUrl = "/assets/images/doctors/minh_tan.png",
                            AverageRating = 5.0,
                            BioEn = "Leading neurologist specialist",
                            BioVi = "Bác sĩ thần kinh, chuyên gia hàng đầu",
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Dr. Lê Minh Tân",
                            Email = "minh.tan@hospital.vn",
                            FullName = "Lê Minh Tân",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            PhoneNumber = "0898765432",
                            PhotoUrl = "/assets/images/doctors/minh_tan.png",
                            RatingCount = 310,
                            SpecialtyId = new Guid("22222222-2222-2222-2222-222222222225"),
                            YearsOfExperience = 20
                        });
                });

            modelBuilder.Entity("MS.Domain.Entities.DoctorAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("DoctorId", "DayOfWeek");

                    b.ToTable("DoctorAvailabilities");
                });

            modelBuilder.Entity("MS.Domain.Entities.DoctorFacility", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasKey("DoctorId", "FacilityId");

                    b.HasIndex("FacilityId");

                    b.ToTable("DoctorFacilities");
                });

            modelBuilder.Entity("MS.Domain.Entities.DoctorLanguage", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.HasKey("DoctorId", "Language");

                    b.ToTable("DoctorLanguages");
                });

            modelBuilder.Entity("MS.Domain.Entities.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Address = "123 Đường Lớn, Hà Nội",
                            City = "Hà Nội",
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DescriptionEn = "The largest general hospital in the region",
                            DescriptionVi = "Bệnh viện đa khoa lớn nhất khu vực",
                            Email = "contact@centralhospital.vn",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            LogoUrl = "/assets/images/facilities/central_hospital.png",
                            NameEn = "Central Hospital",
                            NameVi = "Bệnh viện Trung ương",
                            Phone = "0987654321",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            Address = "201 Nguyễn Văn Cừ, TP. Hồ Chí Minh",
                            City = "TP. Hồ Chí Minh",
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DescriptionEn = "Leading general hospital in the city",
                            DescriptionVi = "Bệnh viện đa khoa hàng đầu thành phố",
                            Email = "info@chorayhospital.vn",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            LogoUrl = "/assets/images/facilities/choray_hospital.png",
                            NameEn = "Cho Ray Hospital",
                            NameVi = "Bệnh viện Chợ Rẫy",
                            Phone = "0898765432",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333335"),
                            Address = "100 Nguyễn Hữu Cảnh, Quận 1",
                            City = "TP. Hồ Chí Minh",
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DescriptionEn = "Leading specialized clinic",
                            DescriptionVi = "Phòng khám chuyên khoa hàng đầu",
                            Email = "contact@saigonclinic.vn",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            LogoUrl = "/assets/images/facilities/saigon_clinic.png",
                            NameEn = "Saigon Clinic",
                            NameVi = "Phòng khám Saigon Clinic",
                            Phone = "0776543210",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333336"),
                            Address = "85 Trần Hưng Đạo, Đà Nẵng",
                            City = "Đà Nẵng",
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DescriptionEn = "Modern dental clinic with advanced technology",
                            DescriptionVi = "Nha khoa hiện đại với công nghệ tiên tiến",
                            Email = "smile@brightdental.vn",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            LogoUrl = "/assets/images/facilities/bright_dental.png",
                            NameEn = "Bright Dental",
                            NameVi = "Nha khoa Rạng Ngời",
                            Phone = "0654321098",
                            Type = 1
                        });
                });

            modelBuilder.Entity("MS.Domain.Entities.FacilitySpecialty", b =>
                {
                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("FacilityId", "SpecialtyId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("FacilitySpecialties");
                });

            modelBuilder.Entity("MS.Domain.Entities.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PatientId", "DoctorId");

                    b.HasIndex("PatientId", "FacilityId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("MS.Domain.Entities.MedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Symptoms")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("MS.Domain.Entities.MessageTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code", "Language")
                        .IsUnique();

                    b.ToTable("MessageTranslations");
                });

            modelBuilder.Entity("MS.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<string>("ContentEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TitleEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MS.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasFilter("[Token] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("MS.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IdentityCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Address = "456 Đường Nhỏ, Hà Nội",
                            AvatarUrl = "/assets/images/patients/nguyenvana.png",
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfBirth = new DateTimeOffset(new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Nguyễn Văn A",
                            Email = "nguyenvana@example.com",
                            FullName = "Nguyễn Văn A",
                            Gender = 0,
                            IdentityCard = "123456789",
                            InsuranceNumber = "987654321",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            PhoneNumber = "0901234567",
                            UserId = new Guid("55555555-5555-5555-5555-555555555558")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444445"),
                            Address = "789 Đường Trung Ương, TP. Hồ Chí Minh",
                            AvatarUrl = "/assets/images/patients/tranthib.png",
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfBirth = new DateTimeOffset(new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Trần Thị B",
                            Email = "tranthib@example.com",
                            FullName = "Trần Thị B",
                            Gender = 1,
                            IdentityCard = "987654321",
                            InsuranceNumber = "123456789",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            PhoneNumber = "0912345678",
                            UserId = new Guid("55555555-5555-5555-5555-555555555559")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444446"),
                            Address = "321 Lê Lợi, Đà Nẵng",
                            AvatarUrl = "/assets/images/patients/phamminhc.png",
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfBirth = new DateTimeOffset(new DateTime(1992, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Phạm Minh C",
                            Email = "phamminhc@example.com",
                            FullName = "Phạm Minh C",
                            Gender = 0,
                            IdentityCard = "456789123",
                            InsuranceNumber = "654321987",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            PhoneNumber = "0923456789"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444447"),
                            Address = "555 Trần Phú, Hải Phòng",
                            AvatarUrl = "/assets/images/patients/hoangthuy.png",
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateOfBirth = new DateTimeOffset(new DateTime(1988, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Hoàng Thúy D",
                            Email = "hoangthuy@example.com",
                            FullName = "Hoàng Thúy D",
                            Gender = 1,
                            IdentityCard = "789123456",
                            InsuranceNumber = "321654987",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            PhoneNumber = "0934567890"
                        });
                });

            modelBuilder.Entity("MS.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("DoctorId", "Rating");

                    b.HasIndex("FacilityId", "Rating");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("MS.Domain.Entities.Specialty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DescriptionEn = "General internal medicine specialty",
                            DescriptionVi = "Chuyên khoa nội tổng quát",
                            DisplayOrder = 1,
                            IconUrl = "/assets/images/specialties/internal_medicine.png",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            NameEn = "General Internal Medicine",
                            NameVi = "Nội tổng quát"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DescriptionEn = "Pediatrics specialty",
                            DescriptionVi = "Chuyên khoa nhi",
                            DisplayOrder = 2,
                            IconUrl = "/assets/images/specialties/pediatrics.png",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            NameEn = "Pediatrics",
                            NameVi = "Nhi khoa"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DescriptionEn = "Cardiology specialty",
                            DescriptionVi = "Chuyên khoa tim mạch",
                            DisplayOrder = 3,
                            IconUrl = "/assets/images/specialties/cardiology.png",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            NameEn = "Cardiology",
                            NameVi = "Tim mạch"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222225"),
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DescriptionEn = "Neurology specialty",
                            DescriptionVi = "Chuyên khoa thần kinh",
                            DisplayOrder = 4,
                            IconUrl = "/assets/images/specialties/neurology.png",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            NameEn = "Neurology",
                            NameVi = "Thần kinh"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222226"),
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DescriptionEn = "Dentistry specialty",
                            DescriptionVi = "Chuyên khoa nha khoa",
                            DisplayOrder = 5,
                            IconUrl = "/assets/images/specialties/dentistry.png",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            NameEn = "Dentistry",
                            NameVi = "Nha khoa"
                        });
                });

            modelBuilder.Entity("MS.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FacilityId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            AvatarUrl = "/assets/images/users/admin.png",
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Admin User",
                            Email = "admin@example.com",
                            FullName = "Administrator",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            PasswordHash = "$2a$12$ImZ30l6CDnzFvnJyM7qbLe.8atsA925OxSiVchotwhB28pSDwUw.K",
                            PhoneNumber = "0999999999",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555556"),
                            AvatarUrl = "/assets/images/users/manager1.png",
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Manager One",
                            Email = "manager1@hospital.vn",
                            FacilityId = new Guid("33333333-3333-3333-3333-333333333333"),
                            FullName = "Quản Lý Một",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            PasswordHash = "$2a$12$hQyTCtbw21Jr/4llbgjb2u4sQk5RMKMqPSdNNR8frCOEt7sLWqf8.",
                            PhoneNumber = "0987654311",
                            Role = 2,
                            Username = "manager1"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555557"),
                            AvatarUrl = "/assets/images/users/doctor1.png",
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Dr. John Doe",
                            Email = "john.doe@example.com",
                            FacilityId = new Guid("33333333-3333-3333-3333-333333333333"),
                            FullName = "John Doe",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            PasswordHash = "$2a$12$zukYCEIMhCO3OgGIl5L1puX/LOy0Snj6cPmfHVOnJkeC6E2YPnP.2",
                            PhoneNumber = "0123456789",
                            Role = 4,
                            Username = "doctor1"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555558"),
                            AvatarUrl = "/assets/images/users/patient1.png",
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Nguyễn Văn A",
                            Email = "nguyenvana@example.com",
                            FullName = "Nguyễn Văn A",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            PasswordHash = "$2a$12$cVF0Xsi11UkJ0k6/5Igxy.VnqyTWl2NO6gEVfHp1cmWIFqgAG27o.",
                            PhoneNumber = "0901234567",
                            Role = 3,
                            Username = "patient1"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555559"),
                            AvatarUrl = "/assets/images/users/patient2.png",
                            CreateBy = "system",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Trần Thị B",
                            Email = "tranthib@example.com",
                            FullName = "Trần Thị B",
                            IsDeleted = false,
                            LastModifiedBy = "system",
                            PasswordHash = "$2a$12$K0UbVa72VJHWS/NNSWiwSuGXrbHFGB7dOnYPJSKK/0HyHMQViiV72",
                            PhoneNumber = "0912345678",
                            Role = 3,
                            Username = "patient2"
                        });
                });

            modelBuilder.Entity("MS.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("MS.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MS.Domain.Entities.Facility", "Facility")
                        .WithMany("Appointments")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MS.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MS.Domain.Entities.Specialty", "Specialty")
                        .WithMany("Appointments")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Facility");

                    b.Navigation("Patient");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("MS.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("MS.Domain.Entities.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MS.Domain.Entities.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("MS.Domain.Entities.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Specialty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MS.Domain.Entities.DoctorAvailability", b =>
                {
                    b.HasOne("MS.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Availabilities")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MS.Domain.Entities.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("MS.Domain.Entities.DoctorFacility", b =>
                {
                    b.HasOne("MS.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Facilities")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MS.Domain.Entities.Facility", "Facility")
                        .WithMany("DoctorFacilities")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("MS.Domain.Entities.DoctorLanguage", b =>
                {
                    b.HasOne("MS.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Languages")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MS.Domain.Entities.FacilitySpecialty", b =>
                {
                    b.HasOne("MS.Domain.Entities.Facility", "Facility")
                        .WithMany("Specialties")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MS.Domain.Entities.Specialty", "Specialty")
                        .WithMany("Facilities")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("MS.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("MS.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Favorites")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MS.Domain.Entities.Facility", "Facility")
                        .WithMany("Favorites")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MS.Domain.Entities.Patient", "Patient")
                        .WithMany("Favorites")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Facility");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MS.Domain.Entities.MedicalRecord", b =>
                {
                    b.HasOne("MS.Domain.Entities.Appointment", "Appointment")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("MS.Domain.Entities.MedicalRecord", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MS.Domain.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MS.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MS.Domain.Entities.Notification", b =>
                {
                    b.HasOne("MS.Domain.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MS.Domain.Entities.Patient", null)
                        .WithMany("Notifications")
                        .HasForeignKey("PatientId");

                    b.HasOne("MS.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MS.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("MS.Domain.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MS.Domain.Entities.Patient", b =>
                {
                    b.HasOne("MS.Domain.Entities.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("MS.Domain.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MS.Domain.Entities.Review", b =>
                {
                    b.HasOne("MS.Domain.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MS.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Reviews")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MS.Domain.Entities.Facility", "Facility")
                        .WithMany("Reviews")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MS.Domain.Entities.Patient", "Patient")
                        .WithMany("Reviews")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Facility");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MS.Domain.Entities.User", b =>
                {
                    b.HasOne("MS.Domain.Entities.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("MS.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("MS.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Availabilities");

                    b.Navigation("Facilities");

                    b.Navigation("Favorites");

                    b.Navigation("Languages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MS.Domain.Entities.Facility", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorFacilities");

                    b.Navigation("Favorites");

                    b.Navigation("Reviews");

                    b.Navigation("Specialties");
                });

            modelBuilder.Entity("MS.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Favorites");

                    b.Navigation("Notifications");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MS.Domain.Entities.Specialty", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Doctors");

                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("MS.Domain.Entities.User", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Notifications");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
